apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwithmaven-deployment
spec:
  replicas: 1  # Number of replicas (Pods) to run
  selector:
    matchLabels:
      app: testwithmaven
  template:
    metadata:
      labels:
        app: testwithmaven
    spec:
      containers:
        - name: testwithmaven
          image: deepika135/testwithmaven:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

